In [1]:
from simple_neural_mpc.robots import Unicycle
from simple_neural_mpc.neural_modeling.dataset import UnicycleDataset
from simple_neural_mpc.neural_modeling.dataset.datamodule import Datamodule
from simple_neural_mpc.utils import project_root
import numpy as np
from simple_neural_mpc.config.neural_config import DatasetConfig

np.set_printoptions(precision=3, suppress=True)

robot = Unicycle()
dataset = None if DatasetConfig.load_data else UnicycleDataset.generate_data(robot)
datamodule = Datamodule(dataset, savedpath=f'{project_root()}/data/unicycle')

[[[-0.147]
  [ 0.203]
  [ 0.064]
  ...
  [-0.105]
  [ 0.326]
  [ 0.127]]

 [[ 0.285]
  [ 0.857]
  [-0.204]
  ...
  [ 0.628]
  [-0.041]
  [ 0.38 ]]

 [[-0.106]
  [ 0.766]
  [ 0.029]
  ...
  [ 0.78 ]
  [ 0.396]
  [ 0.773]]

 ...

 [[ 0.431]
  [-0.142]
  [ 0.703]
  ...
  [-0.08 ]
  [ 0.173]
  [ 0.139]]

 [[ 0.768]
  [ 0.119]
  [ 0.277]
  ...
  [ 0.23 ]
  [ 0.079]
  [ 0.198]]

 [[ 0.052]
  [ 0.063]
  [ 0.731]
  ...
  [ 0.24 ]
  [-0.136]
  [ 0.243]]]


NameError: name 'exit' is not defined

In [2]:
from simple_neural_mpc.neural_modeling.learner.pinn import Pinn

data_range = datamodule.train_data.get_range()
pinn = Pinn(robot, data_range)

In [ ]:
from simple_neural_mpc.neural_modeling.learner.trainer import PinnTrainer

trainer = PinnTrainer()
trainer.fit(pinn, datamodule)

wandb: Currently logged in as: neverorfrog (neverorfrog-sapienza). Use `wandb login --relogin` to force relogin
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /home/neverorfrog/.netrc
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.


GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/neverorfrog/code/simple_neural_mpc/.pixi/envs/default/lib/python3.11/site-packages/lightning/pytorch/loggers/wandb.py:397: There is a wandb run already in progress and newly created instances of `WandbLogger` will reuse this run. If this is not desired, call `wandb.finish()` before instantiating `WandbLogger`.

  | Name | Type       | Params | Mode 
--------------------------------------------
0 | mlp  | Sequential | 16.7 K | train
1 | mse  | MSELoss    | 0      | train
--------------------------------------------
16.7 K    Trainable params
0         Non-trainable params
16.7 K    Total params
0.067     Total estimated model params size (MB)
7         Modules in train mode
0         Modules in eval mode


Epoch 0: 100%|██████████| 200/200 [00:04<00:00, 43.62it/s, v_num=mcfi]     

Metric val/loss improved. New best score: 29.852
Epoch 0, global step 200: 'val/loss' reached 29.85202 (best 29.85202), saving model to '/home/neverorfrog/code/simple_neural_mpc/ckpt/epoch=0-step=200.ckpt' as top 1


Epoch 1: 100%|██████████| 200/200 [00:04<00:00, 40.21it/s, v_num=mcfi]

Metric val/loss improved by 0.132 >= min_delta = 0.0. New best score: 29.720
Epoch 1, global step 400: 'val/loss' reached 29.71960 (best 29.71960), saving model to '/home/neverorfrog/code/simple_neural_mpc/ckpt/epoch=1-step=400.ckpt' as top 1


Epoch 2: 100%|██████████| 200/200 [00:05<00:00, 37.00it/s, v_num=mcfi]

Metric val/loss improved by 0.028 >= min_delta = 0.0. New best score: 29.691
Epoch 2, global step 600: 'val/loss' reached 29.69145 (best 29.69145), saving model to '/home/neverorfrog/code/simple_neural_mpc/ckpt/epoch=2-step=600.ckpt' as top 1


Epoch 3: 100%|██████████| 200/200 [00:05<00:00, 38.41it/s, v_num=mcfi]

Metric val/loss improved by 0.151 >= min_delta = 0.0. New best score: 29.540
Epoch 3, global step 800: 'val/loss' reached 29.53997 (best 29.53997), saving model to '/home/neverorfrog/code/simple_neural_mpc/ckpt/epoch=3-step=800.ckpt' as top 1


Epoch 4: 100%|██████████| 200/200 [00:05<00:00, 38.75it/s, v_num=mcfi]

Epoch 4, global step 1000: 'val/loss' was not in top 1


Epoch 5: 100%|██████████| 200/200 [00:04<00:00, 40.29it/s, v_num=mcfi]

Epoch 5, global step 1200: 'val/loss' was not in top 1


Epoch 6: 100%|██████████| 200/200 [00:04<00:00, 40.71it/s, v_num=mcfi]

Epoch 6, global step 1400: 'val/loss' was not in top 1


Epoch 7: 100%|██████████| 200/200 [00:05<00:00, 36.40it/s, v_num=mcfi]

Epoch 7, global step 1600: 'val/loss' was not in top 1


Epoch 8: 100%|██████████| 200/200 [00:05<00:00, 38.20it/s, v_num=mcfi]

Epoch 8, global step 1800: 'val/loss' was not in top 1


Epoch 9: 100%|██████████| 200/200 [00:05<00:00, 36.41it/s, v_num=mcfi]

Epoch 9, global step 2000: 'val/loss' was not in top 1


Epoch 10:  36%|███▋      | 73/200 [00:02<00:03, 34.63it/s, v_num=mcfi]